spring:
  # 默认 dev 环境
  profiles:
    active: dev
  application.name: thumb-backend
  mvc:
    servlet:
      path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
knife4j:
  enable: true
  setting:
    language: zh_cn
# 整合 Prometheus + Grafana
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    distribution:
      percentiles:
        http:
          server:
            requests: 0.5, 0.75, 0.9, 0.95, 0.99